import { addDays, todayIso } from './format.ts'
import { paidBilling } from './plans.ts'
import type { AppState } from './types.ts'

export const DEMO_PIN = '2026'
export const ADMIN_EMAIL = 'ajithkutten1998@gmail.com'
export const ADMIN_PASSWORD = 'AjithBoutique98@'
export const STUDIO_EMAIL = 'priya@meenakshi.atelier'

const today = todayIso()

export function seedState(): AppState {
  return {
    studios: [
      {
        id: 'stu_meenakshi',
        name: 'Meenakshi Atelier',
        owner: 'Priya',
        phone: '9876501234',
        email: STUDIO_EMAIL,
        city: 'Madurai',
        country: 'India',
        currency: 'INR',
        garments: ['Blouses', 'Lehengas', 'Bridal Wear', 'Custom Tailoring'],
        teamSize: 'Boutique + Tailors',
        createdOn: '2025-11-02',
        isDemo: true,
        billing: paidBilling('studio_pro'),
      },
      {
        id: 'stu_lotus',
        name: 'Lotus Thread',
        owner: 'Lakshmi',
        phone: '9843011122',
        email: 'lakshmi@lotusthread.atelier',
        city: 'Coimbatore',
        country: 'India',
        currency: 'INR',
        garments: ['Sarees', 'Salwar / Churidar', 'Kids Wear'],
        teamSize: 'Small team',
        createdOn: '2026-01-18',
        billing: paidBilling('studio'),
      },
    ],
    users: [
      {
        email: ADMIN_EMAIL,
        name: 'Ajith',
        role: 'admin',
        studioId: null,
        isAdmin: true,
        password: ADMIN_PASSWORD,
      },
      {
        email: STUDIO_EMAIL,
        name: 'Priya',
        role: 'owner',
        studioId: 'stu_meenakshi',
        isAdmin: false,
        password: DEMO_PIN,
      },
      {
        email: 'lakshmi@lotusthread.atelier',
        name: 'Lakshmi',
        role: 'owner',
        studioId: 'stu_lotus',
        isAdmin: false,
        password: DEMO_PIN,
      },
    ],
    customers: [
      {
        id: 'cus_priya',
        studioId: 'stu_meenakshi',
        name: 'Priya Sharma',
        phone: '9876543210',
        whatsapp: '9876543210',
        email: 'priya.sharma@gmail.com',
        city: 'Madurai',
        type: 'bridal',
        tags: ['VIP', 'Bridal', 'Wedding'],
        notes: 'Prefers deep neck. Usually arrives evenings.',
        createdOn: '2025-12-04',
      },
      {
        id: 'cus_anitha',
        studioId: 'stu_meenakshi',
        name: 'Anitha Kumar',
        phone: '9843098765',
        city: 'Madurai',
        type: 'vip',
        tags: ['VIP', 'Frequent'],
        notes: 'Lehenga specialist. Follow up on balance.',
        createdOn: '2026-02-11',
      },
      {
        id: 'cus_meena',
        studioId: 'stu_meenakshi',
        name: 'Meena Iyer',
        phone: '9003214455',
        city: 'Chennai',
        type: 'bridal',
        tags: ['Wedding'],
        createdOn: '2026-06-20',
      },
      {
        id: 'cus_divya',
        studioId: 'stu_lotus',
        name: 'Divya Nair',
        phone: '9442211008',
        city: 'Coimbatore',
        type: 'regular',
        tags: ['Festival'],
        createdOn: '2026-08-01',
      },
    ],
    measurements: [
      {
        id: 'm_current',
        studioId: 'stu_meenakshi',
        customerId: 'cus_priya',
        template: 'Bridal Blouse',
        date: today,
        measuredBy: 'Priya',
        current: true,
        notes: 'Comfortable fit. Extra 0.5" ease.',
        fields: [
          { key: 'bust', label: 'Bust', group: 'BODY', value: '34.0' },
          { key: 'under', label: 'Under bust', group: 'BODY', value: '29.0' },
          { key: 'waist', label: 'Waist', group: 'BODY', value: '28.0' },
          { key: 'hip', label: 'Hip', group: 'BODY', value: '36.0' },
          { key: 'shoulder', label: 'Shoulder', group: 'UPPER BODY', value: '14.0' },
          { key: 'armhole', label: 'Armhole', group: 'UPPER BODY', value: '15.0' },
          { key: 'frontNeck', label: 'Front neck', group: 'UPPER BODY', value: '7.0' },
          { key: 'backNeck', label: 'Back neck', group: 'UPPER BODY', value: '9.0' },
          { key: 'sleeve', label: 'Sleeve length', group: 'SLEEVE', value: '12.0' },
          { key: 'opening', label: 'Sleeve opening', group: 'SLEEVE', value: '9.0' },
        ],
      },
      {
        id: 'm_old',
        studioId: 'stu_meenakshi',
        customerId: 'cus_priya',
        template: 'Reception Blouse',
        date: '2026-06-12',
        measuredBy: 'Meena',
        fields: [
          { key: 'bust', label: 'Bust', group: 'BODY', value: '35.0' },
          { key: 'waist', label: 'Waist', group: 'BODY', value: '29.0' },
          { key: 'shoulder', label: 'Shoulder', group: 'UPPER BODY', value: '14.0' },
        ],
      },
    ],
    styles: [
      {
        id: 'st_maroon',
        studioId: 'stu_meenakshi',
        name: 'Royal Maroon Bridal',
        category: 'Blouse',
        fabric: 'Silk',
        color: 'Maroon',
        neck: 'Deep U',
        sleeve: 'Elbow',
      },
      {
        id: 'st_floral',
        studioId: 'stu_meenakshi',
        name: 'Floral Sleeve',
        category: 'Blouse',
        fabric: 'Cotton silk',
        color: 'Ivory',
        neck: 'Boat',
        sleeve: 'Puff',
      },
      {
        id: 'st_gown',
        studioId: 'stu_meenakshi',
        name: 'Bridal Neck Gown',
        category: 'Gown',
        fabric: 'Organza',
        color: 'Ivory gold',
        neck: 'Illusion',
        sleeve: 'Cap',
      },
    ],
    orders: [
      {
        id: 'AT-1048',
        studioId: 'stu_meenakshi',
        customerId: 'cus_priya',
        type: 'custom',
        occasion: 'wedding',
        items: [{ name: 'Bridal Blouse', qty: 1, price: 8500, styleId: 'st_maroon', measurementId: 'm_current', fabric: 'Silk', color: 'Maroon' }],
        stage: 'stitching',
        assignee: 'Meena',
        deliveryOn: addDays(today, -1),
        deliveryTime: '17:30',
        priority: 'urgent',
        deliveryMethod: 'pickup',
        total: 8500,
        createdOn: addDays(today, -18),
      },
      {
        id: 'AT-1049',
        studioId: 'stu_meenakshi',
        customerId: 'cus_anitha',
        type: 'custom',
        occasion: 'reception',
        items: [{ name: 'Lehenga', qty: 1, price: 16500, fabric: 'Georgette', color: 'Peach' }],
        stage: 'trial',
        assignee: 'Ravi',
        deliveryOn: addDays(today, 15),
        priority: 'normal',
        deliveryMethod: 'pickup',
        total: 16500,
        createdOn: addDays(today, -12),
      },
      {
        id: 'AT-1050',
        studioId: 'stu_meenakshi',
        customerId: 'cus_meena',
        type: 'custom',
        occasion: 'wedding',
        items: [{ name: 'Wedding gown', qty: 1, price: 28000, styleId: 'st_gown' }],
        stage: 'stitching',
        assignee: 'Meena',
        deliveryOn: addDays(today, 1),
        priority: 'urgent',
        deliveryMethod: 'delivery',
        total: 28000,
        createdOn: addDays(today, -9),
      },
      {
        id: 'AT-1051',
        studioId: 'stu_meenakshi',
        customerId: 'cus_priya',
        type: 'custom',
        occasion: 'festival',
        items: [{ name: 'Casual blouse', qty: 2, price: 3200 }],
        stage: 'new',
        deliveryOn: addDays(today, 12),
        priority: 'normal',
        deliveryMethod: 'pickup',
        total: 6400,
        createdOn: today,
      },
      {
        id: 'AT-2101',
        studioId: 'stu_lotus',
        customerId: 'cus_divya',
        type: 'custom',
        occasion: 'festival',
        items: [{ name: 'Kanjeevaram drape blouse', qty: 1, price: 5400 }],
        stage: 'cutting',
        deliveryOn: addDays(today, 8),
        priority: 'normal',
        deliveryMethod: 'pickup',
        total: 5400,
        createdOn: addDays(today, -4),
      },
    ],
    payments: [
      { id: 'pay_1', studioId: 'stu_meenakshi', customerId: 'cus_priya', orderId: 'AT-1048', amount: 3000, method: 'upi', date: addDays(today, -16), reference: 'UPI-8821' },
      { id: 'pay_2', studioId: 'stu_meenakshi', customerId: 'cus_anitha', orderId: 'AT-1049', amount: 4500, method: 'cash', date: addDays(today, -10) },
      { id: 'pay_3', studioId: 'stu_meenakshi', customerId: 'cus_meena', orderId: 'AT-1050', amount: 10000, method: 'bank', date: addDays(today, -8) },
      { id: 'pay_4', studioId: 'stu_lotus', customerId: 'cus_divya', orderId: 'AT-2101', amount: 2000, method: 'upi', date: addDays(today, -3) },
    ],
    trials: [
      { id: 'TR-102', studioId: 'stu_meenakshi', orderId: 'AT-1048', customerId: 'cus_priya', date: addDays(today, -1), time: '17:30', notes: 'Trial overdue — sleeve check' },
      { id: 'TR-103', studioId: 'stu_meenakshi', orderId: 'AT-1049', customerId: 'cus_anitha', date: today, time: '12:30' },
      { id: 'TR-104', studioId: 'stu_meenakshi', orderId: 'AT-1050', customerId: 'cus_meena', date: today, time: '15:00' },
    ],
    appointments: [
      { id: 'ap_1', studioId: 'stu_meenakshi', customerId: 'cus_priya', title: 'Priya — Measurement', date: today, time: '10:00', kind: 'measurement' },
      { id: 'ap_2', studioId: 'stu_meenakshi', customerId: 'cus_anitha', orderId: 'AT-1049', title: 'Anitha — Trial', date: today, time: '12:30', kind: 'trial' },
      { id: 'ap_3', studioId: 'stu_meenakshi', customerId: 'cus_meena', orderId: 'AT-1050', title: 'Meena — Pickup', date: today, time: '15:00', kind: 'pickup' },
    ],
    activity: [
      { id: 'ac_1', studioId: 'stu_meenakshi', at: `${today} 10:32`, who: 'Priya', text: 'Recorded payment ₹3,000 on AT-1048' },
      { id: 'ac_2', studioId: 'stu_meenakshi', at: `${today} 09:15`, who: 'Meena', text: 'Moved AT-1048 Cutting → Stitching' },
      { id: 'ac_3', studioId: 'stu_meenakshi', at: `${addDays(today, -1)} 16:42`, who: 'Priya', text: 'Updated measurement Bust 35 → 34' },
      { id: 'ac_4', studioId: 'stu_lotus', at: `${today} 08:40`, who: 'Lakshmi', text: 'Created order AT-2101 for Divya Nair' },
    ],
  }
}
